
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_EQUALS = 14;
  public static final int TK_MINUS = 8;
  public static final int TK_INT = 24;
  public static final int TK_LPAREN = 2;
  public static final int TK_SEMI = 37;
  public static final int TK_CHAR_CONSTANT = 59;
  public static final int UMINUS = 54;
  public static final int TK_NOT = 21;
  public static final int TK_AND = 22;
  public static final int TK_COMMA = 38;
  public static final int TK_IN = 31;
  public static final int TK_OR = 23;
  public static final int TK_RPAREN = 3;
  public static final int TK_SEQUALS = 20;
  public static final int TK_FLOAT_CONSTANT = 57;
  public static final int TK_COLON_COLON = 40;
  public static final int TK_INTEGER_CONSTANT = 55;
  public static final int TK_FI = 46;
  public static final int TK_IF = 45;
  public static final int TK_RAT = 26;
  public static final int TK_RBRACKET = 5;
  public static final int TK_TDEF = 34;
  public static final int TK_BOOL = 27;
  public static final int TK_DICTIONARY = 28;
  public static final int TK_DOT = 13;
  public static final int TK_OD = 52;
  public static final int TK_IMPLICATION = 15;
  public static final int TK_PLUS = 9;
  public static final int TK_MAIN = 35;
  public static final int TK_RETURN = 42;
  public static final int TK_LARGER = 18;
  public static final int TK_HALF_DECLARATION = 50;
  public static final int TK_TIMES = 10;
  public static final int TK_COLON = 39;
  public static final int TK_TOP = 36;
  public static final int TK_NOTEQUALS = 16;
  public static final int EOF = 0;
  public static final int TK_FDEF = 33;
  public static final int error = 1;
  public static final int TK_WHILE = 49;
  public static final int TK_FLOAT = 25;
  public static final int TK_LBRACE = 6;
  public static final int TK_ELSE = 48;
  public static final int TK_SEQUENCE = 29;
  public static final int TK_READ = 43;
  public static final int TK_ALIAS = 41;
  public static final int TK_BOOLEAN_CONSTANT = 56;
  public static final int TK_RBRACE = 7;
  public static final int TK_LEN = 32;
  public static final int TK_THEN = 47;
  public static final int TK_PRINT = 44;
  public static final int TK_DO = 51;
  public static final int TK_LBRACKET = 4;
  public static final int TK_IDENTIFIER = 60;
  public static final int TK_POWER = 12;
  public static final int TK_ASSIGNMENT = 19;
  public static final int TK_STRING_CONSTANT = 61;
  public static final int TK_RATIONAL_CONSTANT = 58;
  public static final int TK_FORALL = 53;
  public static final int TK_DIVIDE = 11;
  public static final int TK_CHAR = 30;
  public static final int TK_SMALLER = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_LPAREN",
  "TK_RPAREN",
  "TK_LBRACKET",
  "TK_RBRACKET",
  "TK_LBRACE",
  "TK_RBRACE",
  "TK_MINUS",
  "TK_PLUS",
  "TK_TIMES",
  "TK_DIVIDE",
  "TK_POWER",
  "TK_DOT",
  "TK_EQUALS",
  "TK_IMPLICATION",
  "TK_NOTEQUALS",
  "TK_SMALLER",
  "TK_LARGER",
  "TK_ASSIGNMENT",
  "TK_SEQUALS",
  "TK_NOT",
  "TK_AND",
  "TK_OR",
  "TK_INT",
  "TK_FLOAT",
  "TK_RAT",
  "TK_BOOL",
  "TK_DICTIONARY",
  "TK_SEQUENCE",
  "TK_CHAR",
  "TK_IN",
  "TK_LEN",
  "TK_FDEF",
  "TK_TDEF",
  "TK_MAIN",
  "TK_TOP",
  "TK_SEMI",
  "TK_COMMA",
  "TK_COLON",
  "TK_COLON_COLON",
  "TK_ALIAS",
  "TK_RETURN",
  "TK_READ",
  "TK_PRINT",
  "TK_IF",
  "TK_FI",
  "TK_THEN",
  "TK_ELSE",
  "TK_WHILE",
  "TK_HALF_DECLARATION",
  "TK_DO",
  "TK_OD",
  "TK_FORALL",
  "UMINUS",
  "TK_INTEGER_CONSTANT",
  "TK_BOOLEAN_CONSTANT",
  "TK_FLOAT_CONSTANT",
  "TK_RATIONAL_CONSTANT",
  "TK_CHAR_CONSTANT",
  "TK_IDENTIFIER",
  "TK_STRING_CONSTANT"
  };
}

