
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TK_EQUALS = 13;
  public static final int TK_MINUS = 8;
  public static final int TK_INT = 23;
  public static final int TK_LPAREN = 2;
  public static final int TK_SEMI = 35;
  public static final int TK_NOT = 20;
  public static final int TK_AND = 21;
  public static final int TK_COMMA = 36;
  public static final int TK_IN = 30;
  public static final int TK_OR = 22;
  public static final int TK_RPAREN = 3;
  public static final int TK_SEQUALS = 19;
  public static final int TK_FI = 43;
  public static final int TK_IF = 42;
  public static final int TK_RAT = 25;
  public static final int TK_RBRACKET = 5;
  public static final int TK_TDEF = 33;
  public static final int TK_BOOL = 26;
  public static final int TK_DICTIONARY = 27;
  public static final int TK_OD = 48;
  public static final int TK_IMPLICATION = 14;
  public static final int TK_PLUS = 9;
  public static final int TK_MAIN = 34;
  public static final int TK_RETURN = 39;
  public static final int TK_LARGER = 17;
  public static final int TK_TIMES = 10;
  public static final int TK_NUMBER = 50;
  public static final int TK_COLON = 37;
  public static final int TK_NOTEQUALS = 15;
  public static final int EOF = 0;
  public static final int TK_FDEF = 32;
  public static final int error = 1;
  public static final int TK_WHILE = 46;
  public static final int TK_FLOAT = 24;
  public static final int TK_LBRACE = 6;
  public static final int TK_ELSE = 45;
  public static final int TK_SEQUENCE = 28;
  public static final int TK_READ = 40;
  public static final int TK_ALIAS = 38;
  public static final int TK_BOOLEAN_CONSTANT = 51;
  public static final int TK_RBRACE = 7;
  public static final int TK_LEN = 31;
  public static final int TK_THEN = 44;
  public static final int TK_PRINT = 41;
  public static final int TK_DO = 47;
  public static final int TK_LBRACKET = 4;
  public static final int TK_IDENTIFIER = 52;
  public static final int TK_POWER = 12;
  public static final int TK_ASSIGNMENT = 18;
  public static final int TK_FORALL = 49;
  public static final int TK_DIVIDE = 11;
  public static final int TK_CHAR = 29;
  public static final int TK_SMALLER = 16;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "TK_LPAREN",
  "TK_RPAREN",
  "TK_LBRACKET",
  "TK_RBRACKET",
  "TK_LBRACE",
  "TK_RBRACE",
  "TK_MINUS",
  "TK_PLUS",
  "TK_TIMES",
  "TK_DIVIDE",
  "TK_POWER",
  "TK_EQUALS",
  "TK_IMPLICATION",
  "TK_NOTEQUALS",
  "TK_SMALLER",
  "TK_LARGER",
  "TK_ASSIGNMENT",
  "TK_SEQUALS",
  "TK_NOT",
  "TK_AND",
  "TK_OR",
  "TK_INT",
  "TK_FLOAT",
  "TK_RAT",
  "TK_BOOL",
  "TK_DICTIONARY",
  "TK_SEQUENCE",
  "TK_CHAR",
  "TK_IN",
  "TK_LEN",
  "TK_FDEF",
  "TK_TDEF",
  "TK_MAIN",
  "TK_SEMI",
  "TK_COMMA",
  "TK_COLON",
  "TK_ALIAS",
  "TK_RETURN",
  "TK_READ",
  "TK_PRINT",
  "TK_IF",
  "TK_FI",
  "TK_THEN",
  "TK_ELSE",
  "TK_WHILE",
  "TK_DO",
  "TK_OD",
  "TK_FORALL",
  "TK_NUMBER",
  "TK_BOOLEAN_CONSTANT",
  "TK_IDENTIFIER"
  };
}

