
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20141202 (SVN rev 60)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 9;
  public static final int FDEF = 26;
  public static final int SEQUENCE = 23;
  public static final int TDEF = 27;
  public static final int PLUS = 8;
  public static final int INT = 18;
  public static final int SMALLER = 17;
  public static final int RPAREN = 4;
  public static final int THEN = 13;
  public static final int CHAR = 28;
  public static final int IN = 24;
  public static final int IDENTIFIER = 2;
  public static final int LPAREN = 3;
  public static final int LBRACKET = 5;
  public static final int IFEQUALS = 12;
  public static final int RBRACKET = 6;
  public static final int BOOLEAN_CONSTANT = 31;
  public static final int LARGER = 29;
  public static final int EQUALS = 14;
  public static final int NOTEQUALS = 15;
  public static final int FLOAT = 19;
  public static final int NUMBER = 30;
  public static final int EOF = 0;
  public static final int DICTIONARY = 22;
  public static final int DIVIDE = 10;
  public static final int SEQUALS = 16;
  public static final int RAT = 20;
  public static final int MINUS = 7;
  public static final int error = 1;
  public static final int BOOL = 21;
  public static final int LEN = 25;
  public static final int POWER = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "IDENTIFIER",
  "LPAREN",
  "RPAREN",
  "LBRACKET",
  "RBRACKET",
  "MINUS",
  "PLUS",
  "TIMES",
  "DIVIDE",
  "POWER",
  "IFEQUALS",
  "THEN",
  "EQUALS",
  "NOTEQUALS",
  "SEQUALS",
  "SMALLER",
  "INT",
  "FLOAT",
  "RAT",
  "BOOL",
  "DICTIONARY",
  "SEQUENCE",
  "IN",
  "LEN",
  "FDEF",
  "TDEF",
  "CHAR",
  "LARGER",
  "NUMBER",
  "BOOLEAN_CONSTANT"
  };
}

